name: '[CI] PR Assignee 자동 지정'

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Assign PR to the author
      uses: actions/github-script@v6
      with:
        script: |
          const prAuthor = context.payload.pull_request.user.login;
          github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            assignees: [prAuthor]
          })
